### ISSUE TITLE
dropdowns in navbar

### ISSUE THREAD

**Issue by dominikkawka** [MountSionCBSSecondary/SchoolWebsite#28]
The navbar has a blue colour but the dropdowns are still white

**Comment by dominikkawka** [comment]
It wasn't closed, so yes, the dropdowns are still white. personally I think that the website looks better with the white dropdowns, but you'll have to discuss this with the teachers again to see what they would like. I'll keep this open until you decide what to do

**Comment by evanhearne** [comment]
@dominikkawka OK, thanks.

**Comment by evanhearne** [comment]
@dominikkawka I agree with you and because of this, I will close this issue.
