### ISSUE TITLE
The website isn't responsive with phones 

### ISSUE THREAD

**Issue by dominikkawka** [MountSionCBSSecondary/SchoolWebsite#33]
![a](https://user-images.githubusercontent.com/31955648/40176913-d6ce4c00-59d4-11e8-9447-f8f9a88d8a1e.png)

![f](https://user-images.githubusercontent.com/31955648/40181778-d2be3320-59e1-11e8-8aa4-39032c14a50f.png)

**Comment by evanhearne** [comment]
@dominikkawka I just tried out the website on my mobile phone, it seems to be responsive. The problem I believe is with the navigation bar. When I click on buttons that have a drop down menu they don't seem to work.

**Comment by dominikkawka** [comment]
I checked again on my phone just now, the dropdowns seem to work for me, I'll close this pr for now. I remember it not working earlier, I probably just forgot to close this.
