### ISSUE TITLE
Semantic Icons not showing in firefox does in chrome.

### ISSUE THREAD

**Issue by maciejmarchel12** [MountSionCBSSecondary/SchoolWebsite#44]
## Expected Behavior
Icons to show up properly on the page without errors

## Actual Behavior
Icons show up as a error/not found on the firefox browser

![errorfire](https://user-images.githubusercontent.com/31955728/40352150-0d385040-5da6-11e8-8ba2-036f971919bc.png)

## Steps to Reproduce the Problem

  1.Launch the website on firefox

## How to fix
Uninstall firefox and use chrome instead or opera

**Comment by dominikkawka** [comment]
![what](https://user-images.githubusercontent.com/31955648/40365789-59e5e62e-5dcd-11e8-9bc3-186938cea111.png)
idk what you're on about

**Comment by evanhearne** [comment]
@maciejmarchel12 @dominikkawka this is no longer a problem so I will be closing this issue for now however if you find that this issue should be open please ping me to this closed issue.
